python -u executor.py \
    --task_name finetune \
    --pretrain_ckpt_name mae_test_model_jan28.pth \
    --ckpt_name mae_finetuned_jan28.pth \
    --device 4 \
    --run_name finetune_chloro_constraint \
    --feature_wise_rmse False \
    --freeze_encoder True \
    --max_epochs 2 \
    --pretrain_run_name approach1testing \
    --n2one_ft True \
    --encoder_embed_dim 8 \
    --project_name 2dmasking