python -u executor.py \
    --task_name finetune \
    --pretrain_ckpt_name ett_v0.pth \
    --ckpt_name ett_finetuned_v0.pth \
    --device 2 \
    --run_name ettm2_finetune_initial \
    --freeze_encoder True \
    --source_filename ETTm2 \
    --pretrain_run_name ettm2_pretrain_initial \
    --dataset ETT \
    --max_epochs 2